assign:
  strategy:
    # random
    daily-shift-based
  scedule: "*/1 * * * *"
  assignees:
    - Czm369
    - hhaAndroid
    - wanghonglie
    - RangiLyu
    - BIGWangYuDong
    - chhluo
    - ZwwWayne
